=== Gimle/jsman/public/schema/jsman-page.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.jsman.net/xsd/page" xmlns="http://www.jsman.net/xsd/page" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="page">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="heading"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="p"/>
					<xs:element ref="dl"/>
					<xs:element ref="ul"/>
					<xs:element ref="hr"/>
					<xs:sequence>
						<xs:element ref="code"/>
						<xs:element ref="result" minOccurs="0"/>
					</xs:sequence>
					<xs:element ref="section"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="section">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="heading"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="p"/>
					<xs:element ref="dl"/>
					<xs:element ref="ul"/>
					<xs:element ref="hr"/>
					<xs:element ref="code"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="heading">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>

	<xs:element name="p">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="a"/>
				<xs:element ref="b"/>
				<xs:element ref="xref"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="ul">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="li"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="li">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="dl">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:sequence>
					<xs:element ref="dt"/>
					<xs:element ref="dd"/>
				</xs:sequence>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="dt">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>
	<xs:element name="dd">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="a">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="b">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>
	<xs:element name="hr">
		<xs:complexType>
		</xs:complexType>
	</xs:element>

	<xs:element name="code">
		<xs:complexType mixed="true">
			<xs:attribute name="lang" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="result">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="xref">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Gimle/jsman/public/article/substr-vs-substring-vs-slice.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../template/pageWrapper.xsl"?>
<page name="substr vs substring vs slice" xmlns="http://www.jsman.net/xsd/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/page ../schema/jsman-page.xsd">

	<heading>substr vs substring vs slice</heading>

	<p>
		These three methods differ in the parameters, but results in the same primitive string.
		You can stick to one at all times, or pick the best suited one for each use case.
	</p>

	<p>When passing in a negative value as first parameter they handle it differently:</p>

	<dl>
		<dt>substr</dt>
		<dd><p>Some older interpreters (IE8) will treat a negative start index as 0.</p></dd>

		<dt>substring</dt>
		<dd><p>The smallest value will be used as start index. A negative start index will be treated as 0.</p></dd>

		<dt>slice</dt>
		<dd><p>A negative start index is acceptable, and will start counting from the end.</p></dd>
	</dl>

	<p>
		<a href="http://jsperf.com/substring-extraction-methods-substring-substr-slice/">Performance stats at jsperf.com</a>
	</p>

	<p>The constructors</p>

	<dl>
		<dt>String.substr(begin, [length])</dt>
		<dd>
			<p>Starts from <b>begin</b> position and reads <b>length</b> amonut of characters where stop can not be a negative value.</p>
		</dd>

		<dt>String.substring(start, [stop])</dt>
		<dd>
			<p>Starts from <b>start</b> position and stops at <b>stop</b> position where <b>stop</b> can not be a negative value.</p>
		</dd>

		<dt>String.slice(begin, [end])</dt>
		<dd>
			<p>Starts from <b>begin</b> position and ends at <b>end</b> position where <b>end</b> can be a negative value counting from the end.</p>
		</dd>
	</dl>

	<hr/>

	<p>
		Some examples that produce the same result, but have a different set of parameters in the call.
	</p>

	<code>
		var str = 'Hello World';

		console.log(str.substr(1));          // ello World
		console.log(str.substring(1));       // ello World
		console.log(str.slice(1));           // ello World

		console.log(str.substr(-1));         // d
		console.log(str.substring(10));      // d
		console.log(str.slice(-1));          // d

		console.log(str.substr(1, 9));       // ello Worl
		console.log(str.substring(1, 10));   // ello Worl
		console.log(str.slice(1, -1));       // ello Worl

		console.log(str.substr(-4, 3));      // orl
		console.log(str.substring(7, 10));   // orl
		console.log(str.slice(-4, -1));      // orl

		console.log(str.substr(0, 1));       // H
		console.log(str.substring(0, 1));    // H
		console.log(str.slice(0, 1));        // H
	</code>

	<p>Be aware, all of these can run into issues with multibyte characters.</p>

	<code lang="javascript">
		var str = 'हिं';

		console.log(str);                  // हिं
		console.log(str.length);           // 3

		console.log(str.substr(0, 1));     // ह
		console.log(str.substring(0, 1));  // ह
		console.log(str.slice(0, 1));      // ह

		console.log(str.substr(-2, 1));    // ि
		console.log(str.substr(1, 1));     // ि
		console.log(str.substring(1, 2));  // ि
		console.log(str.slice(-2, 2));     // ि
		console.log(str.slice(1, 2));      // ि

		console.log(str.substr(-1));       // ं
		console.log(str.substr(2));        // ं
		console.log(str.substring(2));     // ं
		console.log(str.slice(-1));        // ं
		console.log(str.slice(2));         // ं

	</code>

	<section>
		<heading>Comparing to php</heading>

		<p>Javascript does not have an equal method of php's substr function.</p>

		<p>The substr method lets you work with a length parameter, just like php, but will not accept a negative length. For these cases you can use slice.</p>

		<p>Example php code</p>

		<code lang="php">
			$str = 'Hello World';
			$result = substr($str, 3, 2);     // lo
			$result = substr($str, 1, -2);    // ello Wor
			$result = substr($str, -5, -2);   // Wor
		</code>

		<p>To achieve the same in Javascript you use substr for the first one, and slice for the second one.</p>

		<code>
			var str = 'Hello World';
			console.log(str.substr(3, 2));    // lo
			console.log(str.slice(1, -2));    // ello Wor
			console.log(str.slice(-5, -2));   // Wor
		</code>

		<p>
			You might also want to look at <a href="http://phpjs.org/functions/substr/">substr function at phpjs.org</a>.
		</p>
	</section>

</page>

=== Gimle/jsman/public/article/html-escape.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../template/pageWrapper.xsl"?>
<page name="html escape" xmlns="http://www.jsman.net/xsd/page"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/page ../schema/jsman-page.xsd">

	<heading>html escape</heading>

	<p>
		When working with web development there is often a need to convert special characters in different ways.
	</p>

	<p>
		A simple replace function to replace special characters with their entity representations.
	</p>
	<code>
		const escapeHtml = unsafe => {
			return unsafe
				.replace(/&amp;/g, '&amp;amp;')
				.replace(/&lt;/g, '&amp;lt;')
				.replace(/&gt;/g, '&amp;gt;')
				.replace(/"/g, '&amp;quot;')
				.replace(/'/g, '&amp;#039;')
			;
		};

		console.log(escapeHtml('&lt;foo bar="baz"&gt;&amp;&lt;/foo&gt;'));  // &amp;lt;foo bar=&amp;quot;baz&amp;quot;&amp;gt;&amp;amp;&amp;lt;/foo&amp;gt;
	</code>

	<p>
		If you need to populate a dom node with escaped html, you can simply use textContent instead of innerHTML.
	</p>
	<code>
		document.getElementById('result1').textContent = '';

		let line1 = document.createElement('div');
		let line2 = document.createElement('div');

		line1.innerHTML = '&lt;b&gt;Bold text&lt;/b&gt;';
		line2.textContent = '&lt;b&gt;Bold text&lt;/b&gt;';

		document.getElementById('result1').appendChild(line1);
		document.getElementById('result1').appendChild(line2);
	</code>
	<result id="result1"/>

	<p>
		There is also built in methods for URL encoding of strings. <xref href="manual/1. Standard Global Objects/encodeURI/encodeURI.xml">encodeURI</xref> and <xref href="manual/1. Standard Global Objects/encodeURIComponent/encodeURIComponent.xml">encodeURIComponent</xref> respectively.
	</p>
	<code>
		// Encoding a complete URI will not escape url components like = and &amp;.
		console.log(encodeURI('&lt;foo bar="baz"&gt;&amp;&lt;/foo&gt;'));           // %3Cfoo%20bar=%22baz%22%3E&amp;%3C/foo%3E

		// To encode all special characters:
		console.log(encodeURIComponent('&lt;foo bar="baz"&gt;&amp;&lt;/foo&gt;'));  // %3Cfoo%20bar%3D%22baz%22%3E%26%3C%2Ffoo%3E
	</code>

</page>
