=== Gimle/jsman/public/schema/jsman-manual.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.jsman.net/xsd/manual" xmlns="http://www.jsman.net/xsd/manual" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:simpleType name="nullbool">
		<xs:restriction base="xs:token">
			<xs:enumeration value="true"/>
			<xs:enumeration value="false"/>
			<xs:enumeration value="null"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="method">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="parent" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="operator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="statement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="object">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="lead">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="description">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameters">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="parameter"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string" use="optional"/>
			<xs:attribute name="optional" type="nullbool" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="return">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="changelog">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="change"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="change">
		<xs:complexType mixed="true">
			<xs:attribute name="version" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="ES 6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="notes">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="p">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="a"/>
				<xs:element ref="b"/>
				<xs:element ref="params"/>
				<xs:element ref="xref"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="a">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="b">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>
	<xs:element name="params">
		<xs:complexType>
			<xs:attribute name="separator" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="xref">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="examples">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="example"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="example">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="heading"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="heading"/>
					<xs:element ref="p" minOccurs="0"/>
					<xs:element ref="code"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="heading">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>

	<xs:element name="code">
		<xs:complexType mixed="true">
			<xs:attribute name="lang" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="see-also">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="ul"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="ul">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="li"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="li">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="external">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="mdn"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="mdn">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Math/7. sinh/sinh.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="sinh" parent="Math" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>sinh â€” Returns the inverse hyperbolic sine of a number.</p>
	</lead>
	<description>
		<p>Math.sinh(<params/>)</p>
	</description>
	<parameters>
		<parameter name="number" type="number" optional="false"></parameter>
	</parameters>
	<examples>
		<example>
			<heading>sinh example</heading>
			<code>
				console.log(Math.sinh(1.2));  // 1.5094613554121725
				console.log(Math.sinh(0));    // 0
				console.log(Math.sinh(-3));   // -10.017874927409903
				console.log(Math.sinh('2'));  // 3.626860407847019
			</code>
		</example>

	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Math/sinh">Math.sinh method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/String/startsWith/startsWith.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="startsWith" parent="String" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>startsWith â€” Check if the string ends with this string.</p>
	</lead>
	<description>
		<p>String.startsWith(<params/>)</p>
	</description>
	<parameters>
		<parameter name="string" type="string" optional="false"></parameter>
	</parameters>
	<return>
		<p>boolean primitive.</p>
	</return>
	<changelog>
		<change version="ES 6">Introduced.</change>
	</changelog>
	<examples>
		<example>
			<heading>startsWith example</heading>
			<code>
				console.log('Hello World'.startsWith('World'));   // false
				console.log('Hello World'.startsWith('Hello'));   // true
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith">String.startsWith method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Array/5. splice/splice.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="splice" parent="Array" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>splice — Cuts a piece out of an array, and optionally put in new value(s) in its place.</p>
	</lead>
	<description>
		<p>Array.splice(<params/>)</p>
	</description>
	<parameters>
		<parameter name="start" type="integer" optional="false"></parameter>
		<parameter name="length" type="integer" optional="false"></parameter>
		<parameter name="item, …" type="mixed" optional="true"></parameter>
	</parameters>
	<return>
		<p>The cut out piece array.</p>
	</return>
	<examples>
		<example>
			<heading>splice example</heading>
			<code>
				var array = [2, 4, 8, 16, 32];
				console.log(array);                // [2, 4, 8, 16, 32]
				console.log(array.splice(1, 2));   // [4, 8]
				console.log(array);                // [2, 16, 32]
			</code>
		</example>
		<example>
			<heading>splice example</heading>
			<code>
				var array = [2, 4, 8, 16, 32];
				console.log(array);                         // [2, 4, 8, 16, 32]
				console.log(array.splice(1, 2, 5, 7, 9));   // [4, 8]
				console.log(array);                         // [2, 5, 7, 9, 16, 32]
			</code>
		</example>
		<example>
			<heading>splice example</heading>
			<code>
				var array = [2, 4, 8];
				console.log(array);                    // [2, 4, 8]
				console.log(array.splice(1, 4, 11));   // [4, 8]
				console.log(array);                    // [2, 11]
			</code>
		</example>
		<example>
			<heading>splice example</heading>
			<code>
				var array = [2, 4, 8, 16, 32];
				console.log(array);                                  // [2, 4, 8, 16, 32]
				console.log(array.splice(1, array.length - 2, 11));  // [4, 8, 16]
				console.log(array);                                  // [2, 11, 32]
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/splice">Array.splice method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Boolean/1. toString/toString.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="toString" parent="Boolean" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>toString â€” Returns a string representation of the specified Boolean object.</p>
	</lead>
	<description>
		<p>Boolean.toString(<params/>)</p>
	</description>
	<examples>
		<example>
			<heading>toString example</heading>
			<code>
				var b = new Boolean(true);
				console.log(typeof b.toString()); // Will return "string".
				console.log(b.toString()); // Will be the actial string "true".
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Boolean/toString">Boolean.toString method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/3. Statements/3.2. for … in/for_in.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../template/operatorWrapper.xsl"?>
<statement name="for … in" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../schema/jsman-manual.xsd">
	<lead>
		<p>for … in</p>
	</lead>
	<description>
		<p>for (<params separator=" in"/>)</p>
	</description>
	<parameters>
		<parameter name="variable" type="mixed" optional="false"></parameter>
		<parameter name="object" type="object" optional="false"></parameter>
	</parameters>
	<examples>
		<example>
			<heading>for … in example</heading>
			<p>Iteration between two values.</p>
			<code>
				var obj = {foo: 'Foo', bar: 'Bar'};

				for (var prop in obj) {
					console.log(prop, obj[prop]);
				}
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/for...in">for … in statement</mdn>
	</external>
</statement>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Date/7. toGMTString/toGMTString.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="toGMTString" parent="Date" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>toGMTString – Deprecated.</p>
	</lead>
	<description>
		<p>Date.toGMTString()</p>
	</description>
	<changelog>
		<change version="ES 1">Deprecated.</change>
	</changelog>
	<see-also>
		<ul>
			<li><p><xref href="manual/1. Standard Global Objects/Date/7. toUTCString/toUTCString.xml">Date.toUTCString()</xref></p></li>
		</ul>
	</see-also>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString">Date.toGMTString method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Math/7. acos/acos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="acos" parent="Math" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>acos â€” Returns the arc-cosine (in radians) of a number.</p>
	</lead>
	<description>
		<p>Math.acos(<params/>)</p>
	</description>
	<parameters>
		<parameter name="number" type="number" optional="false">A floating number between -1 and 1.</parameter>
	</parameters>
	<examples>
		<example>
			<heading>acos example</heading>
			<code>
				console.log(Math.acos(0.5));   // 1.0471975511965979
				console.log(Math.acos(4));     // NaN
				console.log(Math.acos(1));     // 0
				console.log(Math.acos(-1));    // 3.141592653589793
				console.log(Math.acos(0));     // 1.5707963267948966
			</code>
		</example>

	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Math/acos">Math.acos method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Array/2.2. from/from.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="from" parent="Array" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>from â€” Creates a new array from an array like input.</p>
	</lead>
	<description>
		<p>Array.from(<params/>)</p>
	</description>
	<parameters>
		<parameter name="array" type="mixed" optional="false">See array below.</parameter>
		<parameter name="callback" type="function" optional="true">See callback below</parameter>
		<parameter name="this" type="object" optional="true"></parameter>
		<section>
			<heading>array</heading>
			<p>An array, or array like input. Something that has a length and indexed items.</p>
		</section>
		<section>
			<heading>callback</heading>
			<p>The following parameters is passed to the callback.</p>
			<dl>
				<dt>value</dt>
				<dd>
					<p>The value of the current index.</p>
				</dd>

				<dt>index</dt>
				<dd>
					<p>The current index.</p>
				</dd>
			</dl>
		</section>
	</parameters>
	<return>
		<p>array</p>
	</return>
	<changelog>
		<change version="ES 6">Introduced.</change>
	</changelog>
	<examples>
		<example>
			<heading>from example</heading>
			<code>
				console.log(Array.from([]));           // []
				console.log(Array.from([1, 2, 3]));    // [1, 2, 3]
				console.log(Array.from(123));          // []
				console.log(Array.from('123'));        // ["1", "2", "3"]
				console.log(Array.from('String'));     // ["S", "t", "r", "i", "n", "g"]
			</code>
			<code>
				var result = Array.from([1, 2, 3], function (value, index) {
					console.log(value, index);
					return value * value;
				});
				console.log(result);     // [1, 4, 9]
			</code>
			<code>
				var result = Array.from(new Set([1, 2, 3]), function (value, index) {
					console.log(value, index);
					return value * value;
				});
				console.log(result);     // [1, 4, 9]
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/from">Array.from method</mdn>
	</external>
</method>
