=== Gimle/jsman/public/schema/jsman-manual.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.jsman.net/xsd/manual" xmlns="http://www.jsman.net/xsd/manual" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:simpleType name="nullbool">
		<xs:restriction base="xs:token">
			<xs:enumeration value="true"/>
			<xs:enumeration value="false"/>
			<xs:enumeration value="null"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="method">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="parent" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="operator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="statement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="object">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="lead">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="description">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameters">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="parameter"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string" use="optional"/>
			<xs:attribute name="optional" type="nullbool" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="return">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="changelog">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="change"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="change">
		<xs:complexType mixed="true">
			<xs:attribute name="version" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="ES 6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="notes">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="p">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="a"/>
				<xs:element ref="b"/>
				<xs:element ref="params"/>
				<xs:element ref="xref"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="a">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="b">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>
	<xs:element name="params">
		<xs:complexType>
			<xs:attribute name="separator" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="xref">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="examples">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="example"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="example">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="heading"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="heading"/>
					<xs:element ref="p" minOccurs="0"/>
					<xs:element ref="code"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="heading">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>

	<xs:element name="code">
		<xs:complexType mixed="true">
			<xs:attribute name="lang" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="see-also">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="ul"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="ul">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="li"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="li">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="external">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="mdn"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="mdn">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Math/7. sin/sin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="sin" parent="Math" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>sin â€” Returns the sine of a number.</p>
	</lead>
	<description>
		<p>Math.sin(<params/>)</p>
	</description>
	<parameters>
		<parameter name="number" type="number" optional="false"></parameter>
	</parameters>
	<examples>
		<example>
			<heading>sin example</heading>
			<code>
				console.log(Math.sin(10));   // -0.5440211108893698
				console.log(Math.sin(0));    // 0
				console.log(Math.sin(-5));   // 0.9589242746631385
				console.log(Math.sin('8'));  // 0.9893582466233818
			</code>
		</example>

	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Math/sin">Math.sin method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Math/7. asin/asin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="asin" parent="Math" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>asin â€” Returns the arc-sine (in radians) of a number.</p>
	</lead>
	<description>
		<p>Math.asin(<params/>)</p>
	</description>
	<parameters>
		<parameter name="number" type="number" optional="false">A number between -1 and 1.</parameter>
	</parameters>
	<examples>
		<example>
			<heading>asin example</heading>
			<code>
				console.log(Math.asin(0.5));   // 0.5235987755982989
				console.log(Math.asin(4));     // NaN
				console.log(Math.asin(1));     // 1.5707963267948966
				console.log(Math.asin(-1));    // -1.5707963267948966
				console.log(Math.asin(0));     // 0
			</code>
		</example>

	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Math/asin">Math.asin method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Date/4.3. setDate/setDate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="setDate" parent="Date" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>setDate – Set the day of the month, according to local time (1–31).</p>
	</lead>
	<description>
		<p>Date.setDate(<params/>)</p>
	</description>
	<parameters>
		<parameter name="day" type="integer" optional="false"></parameter>
	</parameters>
	<return>
		<p>Integer. The new timestamp.</p>
	</return>
	<examples>
		<example>
			<heading>setDate example</heading>
			<code>
				var date = new Date(2015, 9, 21, 16, 29, 00);

				console.log(date.getTime());
				// 1445437740000  (CEST)
				// 1445459340000  (EDT)

				console.log(date.setDate(1));
				// 1443709740000  (CEST)
				// 1443731340000  (EDT)

				console.log(date);              // 01 October 2015 16:29:00
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate">Date.setDate method</mdn>
	</external>
</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/String/indexOf/indexOf.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="indexOf" parent="String" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>indexOf â€” Finds the position of the first occurrence of a string within a string.</p>
	</lead>
	<description>
		<p>String.indexOf(<params/>)</p>
	</description>
	<parameters>
		<parameter name="string" type="string" optional="false"></parameter>
		<parameter name="offset" type="integer" optional="true"></parameter>
	</parameters>
	<return>
		<p>number primitive.</p>
	</return>
	<examples>
		<example>
			<heading>indexOf example</heading>
			<code>
				var txt = 'Hello World';
				console.log(txt.indexOf('o'));  // Will return 4.
				console.log(txt.indexOf('o', 5));  // Will return 7.
				console.log(txt.indexOf('a'));  // Will return -1.
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf">String.indexOf method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/String/charCodeAt/charCodeAt.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="charCodeAt" parent="String" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>charCodeAt â€” Returns the numeric Unicode value of the character at the given index.</p>
	</lead>
	<description>
		<p>String.charCodeAt(<params/>)</p>
	</description>
	<parameters>
		<parameter name="index" type="integer" optional="false">From 0 to string lenght - 1</parameter>
	</parameters>
	<return>
		<p>number primitive.</p>
	</return>
	<examples>
		<example>
			<heading>charCodeAt example</heading>
			<code>
				var str = new String('Foo Bar');
				console.log(str.charCodeAt(4));         // Will return 66.
				console.log(typeof str.charCodeAt(4));  // Will return number.
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt">String.charCodeAt method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/parseInt/parseInt.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../template/objectWrapper.xsl"?>
<object name="parseInt" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../schema/jsman-manual.xsd">
	<lead>
		<p>parseInt â€“ Parses a string as an integer</p>
	</lead>
	<description>
		<p>parseInt(<params/>)</p>
	</description>
	<parameters>
		<parameter name="string" type="string" optional="false"/>
		<parameter name="radix" type="integer" optional="false" default="10">A numeric value between 2 and 36 specifying the representation.</parameter>
	</parameters>
	<return>
		<p>Returns an integer representation of the string.</p>
	</return>
	<examples>
		<example>
			<heading>parseInt example</heading>
			<code>
				console.log(parseInt('123 String'));   // 123
				console.log(parseInt('String 123'));   // NaN
				console.log(parseInt('12'));           // 12
				console.log(parseInt(12));             // 12
				console.log(parseInt('12.42'));        // 12

				console.log(parseInt(Infinity));       // NaN
				console.log(parseInt('Infinity'));     // NaN

				console.log(parseInt('255', 8));       // 173
			</code>
		</example>
	</examples>
	<see-also>
		<ul>
			<li><p><xref href="manual/1. Standard Global Objects/parseFloat/parseFloat.xml">parseFloat</xref></p></li>
		</ul>
	</see-also>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/parseInt">parseInt object</mdn>
	</external>
</object>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Array/8. values/values.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="values" parent="Array" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>values â€” Returns an <xref href="">ArrayIterator</xref> with the values of the array.</p>
	</lead>
	<description>
		<p>Array.values(<params/>)</p>
	</description>
	<changelog>
		<change version="ES 6">Introduced.</change>
	</changelog>
	<examples>
		<example>
			<heading>values example</heading>
			<code>
				var array = [2, 4, 8];
				var keys = array.values();

				console.log(typeof values);  // object
				console.log(values);         // ArrayIterator {}
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/values">Array.values method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Array/3. sort/sort.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="sort" parent="Array" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>sort â€” Sorts an array.</p>
	</lead>
	<description>
		<p>Array.sort(<params/>)</p>
	</description>
	<parameters>
		<parameter name="compare" type="function" optional="true"></parameter>
	</parameters>
	<return>
		<p>The sorted array.</p>
	</return>
	<examples>
		<example>
			<heading>sort example</heading>
			<code>
				var array = [32, 8, 2, 16, 4];
				console.log(array);          // [32, 8, 2, 16, 4]
				console.log(array.sort());   // [16, 2, 32, 4, 8]
				console.log(array);          // [16, 2, 32, 4, 8]
			</code>
		</example>
		<example>
			<heading>sort example</heading>
			<code>
				var array = [32, 8, 2, 16, 4];

				var compare = function (a, b) {
					if (a &lt; b) {
						return -1;
					}
					else if (a &gt; b) {
						return 1;
					}
					return 0;
				};

				console.log(array);                 // [32, 8, 2, 16, 4]
				console.log(array.sort(compare));   // [2, 4, 8, 16, 32]
				console.log(array);                 // [2, 4, 8, 16, 32]
			</code>
			<p>A shorter inline version.</p>
			<code>
				var array = [32, 8, 2, 16, 4];

				console.log(array);                 // [32, 8, 2, 16, 4]
				console.log(array.sort(function (a, b) {
					return a - b;
				}));                                // [2, 4, 8, 16, 32]
				console.log(array);                 // [2, 4, 8, 16, 32]
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/sort">Array.sort method</mdn>
	</external>

</method>
