=== Gimle/jsman/public/schema/jsman-manual.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.jsman.net/xsd/manual" xmlns="http://www.jsman.net/xsd/manual" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:simpleType name="nullbool">
		<xs:restriction base="xs:token">
			<xs:enumeration value="true"/>
			<xs:enumeration value="false"/>
			<xs:enumeration value="null"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="method">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="parent" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="operator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="statement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="object">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lead"/>
				<xs:element ref="description"/>
				<xs:element ref="parameters" minOccurs="0"/>
				<xs:element ref="return" minOccurs="0"/>
				<xs:element ref="changelog" minOccurs="0"/>
				<xs:element ref="notes" minOccurs="0"/>
				<xs:element ref="examples"/>
				<xs:element ref="see-also" minOccurs="0"/>
				<xs:element ref="external"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="lead">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="description">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameters">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="parameter"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string" use="optional"/>
			<xs:attribute name="optional" type="nullbool" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="return">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="changelog">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="change"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="change">
		<xs:complexType mixed="true">
			<xs:attribute name="version" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="ES 6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="notes">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="p">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="a"/>
				<xs:element ref="b"/>
				<xs:element ref="params"/>
				<xs:element ref="xref"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="a">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="b">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>
	<xs:element name="params">
		<xs:complexType>
			<xs:attribute name="separator" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="xref">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="examples">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="example"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="example">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="heading"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="heading"/>
					<xs:element ref="p" minOccurs="0"/>
					<xs:element ref="code"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="heading">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>

	<xs:element name="code">
		<xs:complexType mixed="true">
			<xs:attribute name="lang" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="see-also">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="ul"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="ul">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="li"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="li">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="p"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="external">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="mdn"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="mdn">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Array/3. join/join.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="join" parent="Array" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>join â€” Joins the elements of an array into a string.</p>
	</lead>
	<description>
		<p>Array.join(<params/>)</p>
	</description>
	<parameters>
		<parameter name="separator" type="string" optional="true"></parameter>
	</parameters>
	<return>
		<p>string primitive.</p>
	</return>
	<examples>
		<example>
			<heading>join example</heading>
			<code>
				var array = [2, 4, 8, 16];
				console.log(array);            // [2, 4, 8, 16]
				console.log(array.join());     // 2,4,8,16
				console.log(array.join(';'));  // 2;4;8;16
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/join">Array.join method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Promise/1. then/then.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="then" parent="Promise" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>then — A callback for a resolved Promise. Will execute as soon as the promise is resolved. If the promise is already resolved, it will execute instantly.</p>
	</lead>
	<description>
		<p>Promise.then(<params/>)</p>
	</description>
	<parameters>
		<parameter name="result" type="mixed" optional="true">The result from the resolve function in the promise.</parameter>

	</parameters>
	<changelog>
		<change version="ES 6">
			Introduced.
		</change>
	</changelog>
	<examples>
		<example>
			<heading>Nested example</heading>
			<code>
				new Promise(resolve => {
					resolve('resolved! :)');
				}).then(result => {
					console.log(result);
				});
			</code>
		</example>
		<example>
			<heading>Hook example</heading>
			<code>
				let mypromise = new Promise(resolve => {
					resolve('resolved! :)');
				});

				mypromise.then(result => {
					console.log(result);
				});
			</code>
		</example>
		<example>
			<heading>Resolve after 1 second.</heading>
			<code>
				let mypromise = new Promise(resolve => {
					setTimeout(() => {
						resolve('resolved! :)');
					}, 1000);
				});

				mypromise.then(result => {
					console.log(result);
				});

				console.log('Waiting…');
			</code>
		</example>
		<example>
			<heading>Bind hook 1 second after the promise has already been resolved</heading>
			<code>
				let mypromise = new Promise(resolve => {
					resolve('resolved! :)');
				});

				setTimeout(() => {
					mypromise.then(result => {
						console.log(result);
					});
				}, 1000);

				console.log('Waiting…');
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then">Promise.then method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/3. Statements/2.5. class/class.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../template/operatorWrapper.xsl"?>
<statement name="class" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../schema/jsman-manual.xsd">
	<lead>
		<p>class â€“ Declares a class.</p>
	</lead>
	<description>
		<p>class name <params/></p>
	</description>
	<parameters>
		<parameter name="extends" type="class" optional="true"></parameter>
	</parameters>
	<changelog>
		<change version="ES 6">Introduced.</change>
	</changelog>
	<examples>
		<example>
			<heading>class example</heading>
			<code>
				'use strict';

				class a {
					constructor () {
					}
				}
				console.log(typeof a);   // function

				var b = new a();
				console.log(b);          // a {}
				console.log(typeof b);   // object
			</code>
		</example>
		<example>
			<heading>class example</heading>
			<code>
				'use strict';

				class MyClass {
					myMethod () {
						return 'Hello World';
					}
				}

				var myClass = new MyClass();

				console.log(myClass.myMethod());
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/class">class statement</mdn>
	</external>
</statement>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Math/2.2. ceil/ceil.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="ceil" parent="Math" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>ceil â€” Rounds up to the closest whole number.</p>
	</lead>
	<description>
		<p>Math.ceil(<params/>)</p>
	</description>
	<parameters>
		<parameter name="number" type="number" optional="false"></parameter>
	</parameters>
	<examples>
		<example>
			<heading>ceil example</heading>
			<code>
				console.log(Math.ceil(1));     // 1
				console.log(Math.ceil(1.0));   // 1
				console.log(Math.ceil(1.2));   // 2
				console.log(Math.ceil(1.49));  // 2
				console.log(Math.ceil(1.5));   // 2
				console.log(Math.ceil(1.8));   // 2
				console.log(Math.ceil(2));     // 2
			</code>
		</example>

	</examples>
	<see-also>
		<ul>
			<li><p><xref href="manual/1. Standard Global Objects/Math/2.3. floor/floor.xml">floor</xref></p></li>
			<li><p><xref href="manual/1. Standard Global Objects/Math/2.1. round/round.xml">round</xref></p></li>
		</ul>
	</see-also>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil">Math.ceil method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/JSON/parse/parse.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="parse" parent="JSON" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>parse â€” Parses the input as json.</p>
	</lead>
	<description>
		<p>JSON.parse(<params/>)</p>
	</description>
	<parameters>
		<parameter name="json" type="mixed" optional="false"></parameter>
	</parameters>
	<examples>
		<example>
			<heading>parse example</heading>
			<code>
				console.log(JSON.parse(1.5));                    // 1.5
				console.log(JSON.parse('{"Hello": "World"}'));   // Object {Hello: "World"}
				console.log(JSON.parse('"String"'));             // String
			</code>
		</example>

	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse">JSON.parse method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/Date/5.3. getUTCDate/getUTCDate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="getUTCDate" parent="Date" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>getUTCDate – Get the day of the month, according to universal time (from 1–31).</p>
	</lead>
	<description>
		<p>Date.getUTCDate(<params/>)</p>
	</description>
	<return>
		<p>Integer</p>
	</return>
	<examples>
		<example>
			<heading>Get the local time zone offset.</heading>
			<code>
				console.log(new Date().getUTCDate());  // Gets the current day of the month, according to UTC.
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCDate">Date.getUTCDate method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/String/trim/trim.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../template/methodWrapper.xsl"?>
<method name="trim" parent="String" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../../schema/jsman-manual.xsd">
	<lead>
		<p>trim â€“ Trim away space, tab, new-line, no-break space, etc from beginning and end of string.</p>
	</lead>
	<description>
		<p>String.trim(<params/>)</p>
	</description>
	<return>
		<p>string primitive.</p>
	</return>
	<examples>
		<example>
			<heading>trim example</heading>
			<code>
				console.log('Hello World'.trim());      // Hello World
				console.log('  Hello World  '.trim());  // Hello World
			</code>
			<code>
				console.log(`
					Hello World
					`.trim());      // Hello World
			</code>
		</example>
	</examples>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/trim">String.trim method</mdn>
	</external>

</method>

=== Gimle/jsman/public/manual/1. Standard Global Objects/encodeURIComponent/encodeURIComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../template/objectWrapper.xsl"?>
<object name="encodeURIComponent" xmlns="http://www.jsman.net/xsd/manual"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jsman.net/xsd/manual ../../../schema/jsman-manual.xsd">
	<lead>
		<p>encodeURIComponent</p>
	</lead>
	<description>
		<p>encodeURIComponent(<params/>)</p>
	</description>
	<parameters>
		<parameter name="uriComponent" type="string" optional="false"/>
	</parameters>
	<examples>
		<example>
			<heading>encodeURIComponent example</heading>
			<p>Encodes a url parameter.</p>
			<code>
				var uriComponent = encodeURIComponent('{"foo": ["bar"]}');
				console.log(uriComponent);  // %7B%22foo%22:%20%5B%22bar%22%5D%7D
			</code>
			<p>If used on a url, it will encode it as a parameter.</p>
			<code>
				var uriComponent = encodeURIComponent('http://example.com/');
				console.log(uriComponent);  // http%3A%2F%2Fexample.com%2F
			</code>
		</example>
	</examples>
	<see-also>
		<ul>
			<li><p><xref href="manual/1. Standard Global Objects/encodeURI/encodeURI.xml">encodeURI object</xref></p></li>
		</ul>
	</see-also>
	<external>
		<mdn href="https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent">encodeURIComponent object</mdn>
	</external>
</object>
